import React from "react";
import { BarTask } from "../../types/bar-task";
import { GanttContentMoveAction, RelationMoveTarget } from "../../types/gantt-task-actions";
export declare type TaskItemProps = {
    task: BarTask;
    arrowIndent: number;
    taskHeight: number;
    taskHalfHeight: number;
    relationCircleOffset: number;
    relationCircleRadius: number;
    isProgressChangeable: boolean;
    isDateChangeable: boolean;
    isRelationChangeable: boolean;
    isDelete: boolean;
    isSelected: boolean;
    isRelationDrawMode: boolean;
    rtl: boolean;
    onEventStart: (action: GanttContentMoveAction, selectedTask: BarTask, event?: React.MouseEvent | React.KeyboardEvent) => any;
    onRelationStart: (target: RelationMoveTarget, selectedTask: BarTask) => void;
};
export declare const TaskItem: React.FC<TaskItemProps>;
